model_name: google/flan-t5-base
model_type: AutoModelForSeq2SeqLM
domain_adapter: lora_adapters/dc/dc_amz_en-domain-10_flan-t5-base_lora
intent_adapter: lora_adapters/ic/ic_amz_en-intent-10_flan-t5-base_lora
slot_adapter: lora_adapters/sf-sp/sf-sp_amz_en-slot-10_flan-t5-base_lora
use_accelerate: False
device: mps