model_name: bigscience/bloomz-7b1
model_type: AutoModelForCausalLM
intent_adapter: lora_adapters/ic/ic_multi_woz-intent-10_bloomz-7b1_lora
slot_adapter: lora_adapters/sf-sp/sf-sp_multi_woz-slot-10_bloomz-7b1_lora
use_accelerate: True