model_name: tiiuae/falcon-7b-instruct
model_type: AutoModelForCausalLM
intent_adapter: lora_adapters/ic/ic_multi_woz-intent-10_falcon-7b-instruct_lora
slot_adapter: lora_adapters/sf-sp/sf-sp_multi_woz-slot-10_falcon-7b-instruct_lora
use_accelerate: True