model_name: google-t5/t5-base
model_type: AutoModelForSeq2SeqLM
intent_adapter: lora_adapters/ic/ic_multi_woz-intent-10_t5-base_lora
slot_adapter: lora_adapters/sf-sp/sf-sp_multi_woz-slot-10_t5-base_lora
use_accelerate: False
device: mps