model_name: WizardLM/WizardLM-13B-V1.2
model_type: AutoModelForCausalLM
intent_adapter: lora_adapters/ic/ic_multi_woz-intent-10_WizardLM-13B-V1.2_lora
slot_adapter: lora_adapters/sf-sp/sf-sp_multi_woz-slot-10_WizardLM-13B-V1.2_lora
use_accelerate: True