data_builder: DataBuilderSFSinglePrompt
instruction: "Extraire les informations pertinentes de l'énoncé de l'utilisateur, en tenant compte des libellés et descriptions de slots suivants:\n{{{slot_dict}}}\n"
prompt: "---\nUtilisateur: \"{utterance}\"\nInfo:"