data_builder: DataBuilderSFSinglePrompt
instruction: "Estrai informazioni rilevanti dall'espressione dell'utente, date le seguenti etichette e descrizioni degli slot:\n{{{slot_dict}}}\n"
prompt: "---\nUtente: \"{utterance}\"\nInfo:"