eval_mode: FewShotICEvalConfig
instruction: "Given the following options: \n{intent_options}\n"
prompt: "---\nWhat did the user want when the user said, '{utterance}'? Answer:"
prompt_with_answer: "What did the user want when the user said, '{utterance}'? Answer: {intent}"