output_dir: outputs/
learning_rate: 1e-3
max_steps: 500
warmup_steps: 0
logging_strategy: "steps"
logging_steps: 10
save_strategy: "no"
report_to: "wandb"
fp16: True
auto_find_batch_size: False
per_device_train_batch_size: 4
gradient_accumulation_steps: 4