model_name: bigscience/bloomz-1b7
model_type: AutoModelForCausalLM
intent_adapter: lora_adapters/ic/ic_snips-intent-10_bloomz-1b7_lora
slot_adapter: lora_adapters/sf-sp/sf-sp_snips-slot-10_bloomz-1b7_lora
device: "mps"
use_accelerate: False