model_name: tiiuae/falcon-7b-instruct
model_type: AutoModelForCausalLM
intent_adapter: lora_adapters/ic/ic_snips-intent-10_falcon-7b-instruct_lora
slot_adapter: lora_adapters/sf-sp/sf-sp_snips-slot-10_falcon-7b-instruct_lora
use_accelerate: True