model_name: lmsys/vicuna-13b-v1.5
model_type: AutoModelForCausalLM
intent_adapter: lora_adapters/ic/ic_snips-intent-10_vicuna-13b-v1.5_lora
slot_adapter: lora_adapters/sf-sp/sf-sp_snips-slot-10_vicuna-13b-v1.5_lora
use_accelerate: True